# Generated by Django 5.2.1 on 2025-06-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, help_text='Optional profile picture for the author', null=True, upload_to='authors/avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A URL-friendly identifier derived from title.', max_length=150, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Short summary of the post (e.g. first 1–2 sentences).')),
                ('image', models.URLField(blank=True, help_text='URL to a featured image (or use ImageField if you serve/upload media).', max_length=500)),
                ('published_at', models.DateTimeField(db_index=True, help_text='When the post was (or will be) published.')),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured post (e.g. for homepage slider).')),
                ('read_time', models.CharField(blank=True, help_text="Estimated read time, e.g. '5 min read'.", max_length=20)),
                ('content', models.TextField(help_text='Full HTML or Markdown content of the post.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='BlogApi.author')),
                ('category', models.ForeignKey(help_text='Select a category for this post.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='BlogApi.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='BlogApi.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the commenter', max_length=80)),
                ('email', models.EmailField(help_text='Email of the commenter', max_length=254)),
                ('content', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck to hide comment without deleting.')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BlogApi.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published_at'], name='blogApi_pos_publish_d8398d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blogApi_pos_slug_506780_idx'),
        ),
    ]
