# Generated by Django 5.2.1 on 2025-06-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_galleries/')),
            ],
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='BlogApi_pos_publish_d539a2_idx',
            old_name='blogApi_pos_publish_d8398d_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='BlogApi_pos_slug_07d0d0_idx',
            old_name='blogApi_pos_slug_506780_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='post_gallery_images',
            field=models.ManyToManyField(blank=True, help_text='PostGalleryImages related to this post.', related_name='posts', to='BlogApi.postgalleryimage'),
        ),
    ]
