# Generated by Django 5.2.1 on 2025-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0002_postgalleryimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_gallery_images',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the post was (or will be) published.', null=True),
        ),
        migrations.DeleteModel(
            name='PostGalleryImage',
        ),
    ]
