# Generated by Django 5.2.1 on 2025-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0003_remove_post_post_gallery_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
