services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis-Backend
    hostname: redis
    profiles:
      - dev
      - full_run
    networks:
      - redis-net
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    environment:
        REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    image: postgres:14.7-alpine
    container_name: database-Backend
    hostname: db
    profiles:
      - dev
      - full_run
    networks:
      - db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    profiles:
      - full_run
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_TYPE: $DATABASE_TYPE
      DATABASE_HOST: db
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_LOGIN: $EMAIL_LOGIN
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_SMTP_PORT: $EMAIL_SMTP_PORT
      EMAIL: $EMAIL
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      PAGE_CACHE_TIME: PAGE_CACHE_TIME
      DJANGO_SUPERUSER_USERNAME: $DJANGO_SUPERUSER_USERNAME
      DJANGO_SUPERUSER_PASSWORD: $DJANGO_SUPERUSER_PASSWORD
      DJANGO_SUPERUSER_EMAIL: $DJANGO_SUPERUSER_EMAIL
    ports:
      - 8000:8000


networks:
  redis-net:
      ipam:
        config:
          - subnet: 172.25.1.0/24
            gateway: 172.25.1.1
  db:
    ipam:
      config:
        - subnet: 172.25.2.0/24
          gateway: 172.25.2.1

volumes:
  postgres_data:
  redis_data: