# Generated by Django 5.2.1 on 2025-06-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('map_iframe', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IconsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the icon (e.g., GitHub, LinkedIn)', max_length=100, verbose_name='Name')),
                ('class_name', models.CharField(help_text="CSS class categorry_title for the icon (e.g., 'fab fa-github')", max_length=100, verbose_name='Class Name')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('iso_code', models.CharField(max_length=3, verbose_name='ISO Code')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Technical Arsenal Name')),
                ('company', models.CharField(max_length=100, verbose_name='Technical Arsenal Company')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Technical Arsenal Description')),
            ],
            options={
                'verbose_name': 'Professional Journey',
            },
        ),
        migrations.CreateModel(
            name='TechnicalArsenalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Technical Arsenal Skill')),
            ],
            options={
                'verbose_name': 'Technical Arsenal Skill',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.iconsclass', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'core value',
                'verbose_name_plural': 'core values',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lang', to='api.lang'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill list (e.g., Programming Languages, Frameworks)', max_length=100, verbose_name='Name')),
                ('icon_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='api.iconsclass')),
            ],
            options={
                'verbose_name': 'Skill List',
                'verbose_name_plural': 'Skill Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(help_text='Name of skills card', max_length=100, verbose_name='Category title')),
                ('icon_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_cards', to='api.iconsclass')),
                ('skills', models.ManyToManyField(to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalArsenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Technical Arsenal Title')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iconsclass')),
                ('skills', models.ManyToManyField(blank=True, to='api.technicalarsenalskill', verbose_name='Skills')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100, verbose_name='About Title')),
                ('about_text', models.TextField(verbose_name='About Text')),
                ('core_value', models.ManyToManyField(related_name='about_core_value', to='api.corevalue')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_lang', to='api.lang', unique=True)),
                ('professional_journey', models.ManyToManyField(related_name='about_professional_journey', to='api.professionaljourney')),
                ('technical_arsenal', models.ManyToManyField(related_name='about_technical_arsenal', to='api.technicalarsenal')),
                ('testimonials', models.ManyToManyField(related_name='about_testimonials', to='api.testimonials')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
    ]
