# Generated by Django 5.2.1 on 2025-06-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the social link (e.g., GitHub, LinkedIn)', max_length=100, verbose_name='Name')),
                ('url', models.URLField(help_text='URL of the social link', verbose_name='URL')),
                ('footer', models.BooleanField(default=False, help_text='Whether to display this link in the footer', verbose_name='Footer')),
                ('contact_pages', models.BooleanField(default=False, help_text='Whether to display this link on contact pages', verbose_name='Contact Pages')),
                ('about_pages', models.BooleanField(default=False, help_text='Whether to display this link on about pages', verbose_name='About Pages')),
                ('icon_class', models.ForeignKey(help_text="Icon associated with the social link (e.g., 'fab fa-github')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='api.iconsclass', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['name'],
            },
        ),
    ]
