# Generated by Django 5.2.1 on 2025-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.RemoveField(
            model_name='technicalarsenalskill',
            name='technical_arsenal',
        ),
        migrations.AddField(
            model_name='about',
            name='core_value',
            field=models.ManyToManyField(related_name='about_core_value', to='api.corevalue'),
        ),
        migrations.AlterField(
            model_name='technicalarsenal',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.technicalarsenalskill', verbose_name='Skills'),
        ),
    ]
