# Generated by Django 5.2.1 on 2025-06-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='lang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_lang', to='api.lang'),
        ),
    ]
