# Generated by Django 5.2.1 on 2025-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_faq_language_alter_contact_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='core_value',
            field=models.ManyToManyField(blank=True, related_name='about_core_value', to='api.corevalue'),
        ),
        migrations.AlterField(
            model_name='about',
            name='professional_journey',
            field=models.ManyToManyField(blank=True, related_name='about_professional_journey', to='api.professionaljourney'),
        ),
        migrations.AlterField(
            model_name='about',
            name='technical_arsenal',
            field=models.ManyToManyField(blank=True, related_name='about_technical_arsenal', to='api.technicalarsenal'),
        ),
        migrations.AlterField(
            model_name='about',
            name='testimonials',
            field=models.ManyToManyField(blank=True, related_name='about_testimonials', to='api.testimonials'),
        ),
        migrations.AlterField(
            model_name='iconsclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='professionaljourney',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='professionaljourney',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='professionaljourney',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Job title'),
        ),
    ]
