# Generated by Django 5.2.1 on 2025-06-21 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_about_core_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='url',
            field=models.URLField(help_text='URL of the social link', validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto'])], verbose_name='URL'),
        ),
    ]
