# Generated by Django 5.2.1 on 2025-06-21 17:23

import api.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sociallinks_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='url',
            field=models.CharField(help_text='URL of the social link', max_length=200, validators=[api.validator.validate_url_or_mailto], verbose_name='URL'),
        ),
    ]
