# Generated by Django 5.2.1 on 2025-06-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sociallinks_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='language',
        ),
    ]
