# Generated by Django 5.2.1 on 2025-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_faq_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sub_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Sub Title'),
        ),
    ]
