# Generated by Django 5.2.1 on 2025-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_about_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='Sub Title'),
        ),
    ]
