# Generated by Django 5.2.1 on 2025-06-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_about_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='core_value',
        ),
        migrations.RemoveField(
            model_name='about',
            name='professional_journey',
        ),
        migrations.RemoveField(
            model_name='about',
            name='technical_arsenal',
        ),
        migrations.RemoveField(
            model_name='about',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='professionaljourney',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='About_ProfessionalJourney'),
        ),
        migrations.AddField(
            model_name='technicalarsenal',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Technical Arsenal Skill'),
        ),
        migrations.AddField(
            model_name='technicalarsenalskill',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Technical Arsenal Skill'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Technical Arsenal Skill'),
        ),
        migrations.AlterField(
            model_name='professionaljourney',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
