# Generated by Django 5.2.1 on 2025-06-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_about_core_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalarsenal',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='technicalarsenalskill',
            name='about',
        ),
        migrations.AddField(
            model_name='technicalarsenalskill',
            name='technical_arsenal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.technicalarsenal', verbose_name='Technical Arsenal Skill'),
        ),
    ]
