# Generated by Django 5.2.1 on 2025-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_technicalarsenal_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalarsenalskill',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Technical Arsenal Skill'),
        ),
    ]
