# Generated by Django 5.2.1 on 2025-06-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_technicalarsenalskill_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevalue',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Core value about'),
        ),
    ]
