# Generated by Django 5.2.1 on 2025-06-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_corevalue_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Core value about'),
        ),
        migrations.AlterField(
            model_name='technicalarsenal',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Technical Arsenal Skill'),
        ),
        migrations.AlterField(
            model_name='technicalarsenalskill',
            name='technical_arsenal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technicalarsenal', verbose_name='Technical Arsenal Skill'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Technical Arsenal Skill'),
        ),
    ]
