# Generated by Django 5.2.1 on 2025-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_corevalue_about_alter_technicalarsenal_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Image'),
        ),
    ]
