# Generated by Django 5.2.1 on 2025-06-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Core value about'),
        ),
    ]
