# Generated by Django 5.2.1 on 2025-06-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_corevalue_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.about', verbose_name='Core value about'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iconsclass', verbose_name='icon'),
        ),
    ]
