# Generated by Django 5.2.1 on 2025-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_corevalue_about_alter_corevalue_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='About Image'),
        ),
    ]
