# Generated by Django 5.2.1 on 2025-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='core_value_title',
            field=models.CharField(default='Forging Principles', max_length=100, verbose_name='Core Value Title'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_title',
            field=models.CharField(default='The Master Behind the Mask', max_length=100, verbose_name='Image Title'),
        ),
        migrations.AddField(
            model_name='about',
            name='professional_journal_title',
            field=models.CharField(default="The Smith's Journey", max_length=100, verbose_name='Professional Journal Title'),
        ),
        migrations.AddField(
            model_name='about',
            name='technical_arsenal_title',
            field=models.CharField(default='Arsenal of Expertise', max_length=100, verbose_name='Technical Arsenal Title'),
        ),
        migrations.AddField(
            model_name='about',
            name='testimonials_title',
            field=models.CharField(default='Testimonials', max_length=100, verbose_name='Testimonials Title'),
        ),
    ]
