# Generated by Django 5.2.1 on 2025-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_about_core_value_title_about_image_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='testimonials_title',
            field=models.CharField(default='Tales from the Guild', max_length=100, verbose_name='Testimonials Title'),
        ),
    ]
