# Generated by Django 5.2.1 on 2025-08-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='budget',
            field=models.CharField(max_length=100, null=True, verbose_name='Budget'),
        ),
    ]
