# Generated by Django 5.2.1 on 2025-06-06 19:27

import Images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guild name')),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alternative text')),
            ],
            options={
                'ordering': ['alt', 'name'],
            },
        ),
    ]
