# Generated by Django 5.2.1 on 2025-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0001_initial'),
        ('api', '0003_alter_about_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_technologies',
            field=models.ManyToManyField(related_name='full_technologies', to='api.iconsclass'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_technologies',
            field=models.ManyToManyField(related_name='main_technologies', to='api.iconsclass'),
        ),
    ]
