# Generated by Django 5.2.1 on 2025-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
