# Generated by Django 5.2.1 on 2025-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0002_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
