# Generated by Django 5.2.1 on 2025-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0002_project_full_technologies_project_main_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='ProjectApi.projectcategory'),
        ),
    ]
