# Generated by Django 5.2.1 on 2025-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0003_remove_project_status_projectdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='short',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
