# Generated by Django 5.2.1 on 2025-06-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0004_alter_project_demo_url_alter_project_documents_url_and_more'),
        ('api', '0003_alter_about_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_technologies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('full_technologies', models.ManyToManyField(related_name='full_technologies', to='api.iconsclass')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_details', to='ProjectApi.projectdetail'),
        ),
    ]
