# Generated by Django 5.2.1 on 2025-06-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0005_remove_project_client_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_details',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.project'),
        ),
    ]
