# Generated by Django 5.2.1 on 2025-06-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0006_remove_project_project_details_projectdetail_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.project', unique=True),
        ),
    ]
