# Generated by Django 5.2.1 on 2025-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0007_alter_keyfeatures_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='short',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
