# Generated by Django 5.2.1 on 2025-06-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0008_projectcategory_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='short',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
