# Generated by Django 5.2.1 on 2025-06-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0009_alter_projectcategory_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProjectApi.project'),
        ),
    ]
