# Generated by Django 5.2.1 on 2025-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0010_alter_keyfeatures_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(upload_to='project_gallery/'),
        ),
    ]
