# Generated by Django 5.2.1 on 2025-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0011_alter_projectgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
