# Generated by Django 5.2.1 on 2025-06-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0012_alter_projectcategory_category_name'),
        ('api', '0022_alter_about_testimonials_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.iconsclass'),
        ),
    ]
