# Generated by Django 5.2.1 on 2025-06-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0013_projectcategory_icon'),
        ('api', '0022_alter_about_testimonials_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.iconsclass'),
        ),
    ]
