# Generated by Django 5.2.1 on 2025-06-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApi', '0014_alter_projectcategory_icon'),
        ('api', '0022_alter_about_testimonials_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.iconsclass'),
        ),
    ]
